### ISSUE TITLE
Link to Raspbian image with OC_manager installed does not work

### ISSUE THREAD

**Issue by dallonjp** [OfficeChromatography/OC_manager#2]
The link https://jlubox.uni-giessen.de/getlink/fiLFUwBzvcCbUtiws9tct3df/RPI_OC_20180605.img.gz[] does not work. The github page just reloads and nothing downloads.

**Comment by DimitriF** [comment]
It seems my account on jlubox had been deactivated. I still have the image and will put it on MEGA.

**Comment by dallonjp** [comment]
Awesome! Thank you. Could you please let me know when it is active?

**Comment by DimitriF** [comment]
I used google drive, here is the new link: https://drive.google.com/open?id=1Xfa_m9dpSYnHOup1OospvOuhAxPW0mfq
Thanks for spotting it
